### ISSUE TITLE
Broken since 1.1.0

### ISSUE THREAD

**Issue by wallin** [athombv/com.danfoss#10]
Since the update 1.1.0 was installed, the app is no longer working. There is a warning icon next to the app in my list of apps and the message is:

```
Stack trace:

Error: Cannot find module 'homey-log'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/app.js:3:13)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: 1
Exit signal: null
```

I'm using Homey app v1.0.2

**Comment by Rob-Houweling** [comment]
Same here:
Stack trace:

Error: Cannot find module 'homey-log'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/app.js:3:13)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: 1
Exit signal: null

**Comment by RobinBol** [comment]
Fixed!

**Comment by Rob-Houweling** [comment]
Can I force an update?
