### ISSUE TITLE
RangeError: index out of range after about 2 months of operation

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/com.danfoss#8]
I'm not sure if this helps in getting this app more stable. If you need more info, don't hesitate to contact me.

After about 2 Months of operation, the app had an error:
Stack trace:

RangeError: index out of range
at checkOffset (buffer.js:688:11)
at Buffer.readUIntBE (buffer.js:712:5)
at Object.module.exports.ZwaveDriver.capabilities.measure_battery.target_temperature.command_report_parser.report [as command_report_parser] (/drivers/LC13/driver.js:55:32)
at CommandClass.<anonymous> (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:484:45)
at emitThree (events.js:97:13)
at CommandClass.emit (events.js:175:7)
at /homey-app/wireless/zwave.js:26:25
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)

Turning the app off and on restored the functionality.

**Comment by RobinBol** [comment]
Thanks for reporting your issue! I have made some changes to the app that will prevent this from happening in the future.
